import { test, expect } from '@playwright/test';
import { pdf } from '../../server/tests/helpers.js';
import { educationDocumentLines } from '../../server/tests/educationFixtures.js';

test('education evidence journey, specific product, variation review and lender-review readiness', async ({page}) => {
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/register');
  await page.getByLabel('Full name').fill('Riya Sharma');
  await page.getByLabel('Email address').fill(`education-${Date.now()}@example.test`);
  await page.getByLabel('Password',{exact:true}).fill('Password1!');
  await page.getByLabel('Date of birth').fill('2003-06-15');
  await page.getByLabel('City (optional)').fill('Delhi');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Hello, Riya.'})).toBeVisible();
  await page.goto('/loans');await page.getByRole('radio',{name:/Education Loan/}).check();await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByLabel('Age',{exact:true}).fill('23');await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByLabel('Employment',{exact:true}).selectOption('student');
  await page.getByRole('spinbutton',{name:'Monthly income',exact:true}).fill('25000');await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByLabel('Loan amount',{exact:true}).fill('500000');await page.getByLabel('Tenure (years)').fill('10');await page.getByRole('button',{name:'Continue',exact:true}).click();
  await page.getByRole('radio',{name:/750\+/}).check();await page.getByRole('button',{name:'View requirements',exact:true}).click();
  await expect(page.getByRole('heading',{name:'NOT READY',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Applicant income evidence',exact:true})).toBeVisible();
  const copilot = page.getByRole('complementary', {name:'SUBMIT SARTHI'});
  await page.getByRole('button',{name:'SUBMIT SARTHI',exact:true}).click();
  await expect(copilot).toContainText('DEMO/MOCK');
  await copilot.getByRole('button',{name:'Why am I not ready?',exact:true}).click();
  await expect(copilot.getByRole('region',{name:'Submit Sarthi response'})).toContainText('NOT READY');
  await copilot.getByRole('button',{name:'What should I fix next?',exact:true}).click();
  await expect(copilot.getByRole('region',{name:'Submit Sarthi response'})).toContainText('priority order');
  await copilot.getByRole('button',{name:'Close Submit Sarthi'}).click();
  async function upload(type,lines){
    await page.goto(`/documents/upload?type=${type}`);
    await page.getByLabel('Choose document',{exact:true}).setInputFiles({name:`${type}.pdf`,mimeType:'application/pdf',buffer:pdf(lines)});
    await page.getByRole('checkbox',{name:/I consent to SubmitSafe analyzing/}).check();await page.getByRole('button',{name:'Upload & check document'}).click();
    await expect(page.getByRole('heading',{name:'Document Check Complete'})).toBeVisible();
    if(['AADHAAR','PAN','DRIVING_LICENCE'].includes(type))await expect(page.getByText('SOURCE_NOT_VERIFIED',{exact:true})).toBeVisible();
  }
  for(const [type,lines] of Object.entries(educationDocumentLines))if(type!=='DRIVING_LICENCE')await upload(type,lines);
  await page.goto('/documents');await expect(page.getByRole('heading',{name:'READY FOR LENDER REVIEW',exact:true})).toBeVisible();
  await expect(page.getByText('PASS WITH VERIFICATION LIMITATION',{exact:true}).first()).toBeVisible();
  await expect(page.getByRole('link',{name:'Demo Student Tuition Support',exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  if(process.env.SCREENSHOT_DIR)await page.screenshot({path:`${process.env.SCREENSHOT_DIR}/education-ready-mobile.png`,fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('link',{name:'View configured bank products',exact:true}).click();
  await expect(page.locator('.loan-card')).toHaveCount(3);
  await expect(page.locator('.loan-card').first()).toContainText('EDUCATION LOAN');
  await page.locator('.loan-card').nth(0).getByRole('checkbox',{name:'Compare',exact:true}).check();
  await page.locator('.loan-card').nth(1).getByRole('checkbox',{name:'Compare',exact:true}).check();
  await page.getByRole('link',{name:'Compare lenders',exact:true}).click();
  await expect(page.locator('.comparison-table')).toContainText('Admission letter');
  await page.goto('/loans/results');
  await page.locator('.loan-card').filter({hasText:'Study Credit Demo Education Loan'}).getByRole('link',{name:'Prepare Application',exact:true}).click();
  await expect(page.getByText('NOT READY',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Continue preparing',exact:true}).click();
  await expect(page.getByText(/Specific product: Study Credit/)).toBeVisible();
  await upload('DRIVING_LICENCE',educationDocumentLines.DRIVING_LICENCE.map(s=>s.replace('Riya Sharma','Riya S Sharma')));
  await page.goto('/documents');await expect(page.getByRole('heading',{name:'REVIEW REQUIRED',exact:true})).toBeVisible();
  await expect(page.getByText('POSSIBLE_MATCH',{exact:true}).first()).toBeVisible();
  await page.getByRole('button',{name:'SUBMIT SARTHI',exact:true}).click();
  await copilot.getByRole('button',{name:'What information conflicts?',exact:true}).click();
  await expect(copilot.getByRole('region',{name:'Submit Sarthi response'})).toContainText('POSSIBLE_MATCH');
  await copilot.getByRole('button',{name:'Close Submit Sarthi'}).click();
  if(process.env.SCREENSHOT_DIR)await page.screenshot({path:`${process.env.SCREENSHOT_DIR}/education-review-desktop.png`,fullPage:true,animations:'disabled'});
  await upload('DRIVING_LICENCE',educationDocumentLines.DRIVING_LICENCE);
  await page.reload();await expect(page.getByText('SOURCE_NOT_VERIFIED',{exact:true})).toBeVisible();
  await page.goto('/documents');await expect(page.getByRole('heading',{name:'READY FOR LENDER REVIEW',exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'SUBMIT SARTHI',exact:true}).click();
  await copilot.getByRole('button',{name:'Why am I not ready?',exact:true}).click();
  await expect(copilot.getByRole('region',{name:'Submit Sarthi response'})).toContainText('READY FOR LENDER REVIEW');
  await expect(copilot).toContainText('7 requirements satisfied');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  if(process.env.SCREENSHOT_DIR)await page.screenshot({path:`${process.env.SCREENSHOT_DIR}/copilot-ready-mobile.png`,animations:'disabled'});
  await copilot.getByRole('button',{name:'Close Submit Sarthi'}).click();
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('link',{name:'Review selected product',exact:true}).click();
  await page.getByRole('link',{name:/Apply Directly/}).click();
  await page.getByRole('checkbox',{name:/I consent to sharing my application/}).check();
  await page.getByRole('button',{name:'Prepare Application',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.locator('.application-code strong')).toHaveText(/SS-EDUCATION-\d{4}-\d{5}/);
  await page.getByRole('link',{name:'View my application'}).click();
  await expect(page.getByRole('heading',{name:'Your application, at a glance.'})).toBeVisible();
  await expect(page.locator('.page-heading')).toContainText('Study Credit');
  await page.goto('/profile');await page.getByText('Edit applicant details',{exact:true}).click();
  await page.getByLabel('Applicant full name').fill('Riya S Sharma');await page.getByRole('button',{name:'Save applicant profile'}).click();
  await expect(page.locator('.profile-heading')).toContainText('Riya S Sharma');
  await page.goto('/documents');await expect(page.getByRole('heading',{name:'REVIEW REQUIRED',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});
