import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { MapPin, Languages, ArrowRight, UsersRound, ShieldCheck, Check } from 'lucide-react';
import { api } from '../services/api';
import { useResource } from '../hooks/useResource';
import { useApp } from '../context/AppContext';
import { Button, PageHeading, Loading, Problem, Badge, Select, CheckList, DetailRow, Notice, Modal } from '../components/UI';
function Avatar({name,index=0}){return <div className={`agent-avatar avatar-${index%3}`} role="img" aria-label={`Illustrated avatar for ${name}`}><svg viewBox="0 0 100 100" fill="none" aria-hidden="true"><path d="M13 100c2-30 17-43 37-43s36 13 38 43" fill="#315c4c"/><ellipse cx="50" cy="39" rx="22" ry="27" fill="#dcbf95"/><path d="M27 35c-2-25 35-37 46-11l-2 13-9-16c-10 8-21 11-35 14Z" fill="#263e32"/><path d="M43 52q7 5 14 0" stroke="#745840" strokeWidth="2" strokeLinecap="round"/><circle cx="42" cy="39" r="1.5" fill="#263e32"/><circle cx="60" cy="39" r="1.5" fill="#263e32"/><path d="m38 66 12 15 13-15" stroke="#e8e9d2" strokeWidth="4"/></svg></div>;}
export function Agents(){const resource=useResource('agents',api.agents);const [city,setCity]=useState('All cities');if(resource.loading)return <Loading label="Finding a little expert support…"/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;const agents=resource.data.data;return <div className="container page"><PageHeading eyebrow="YOU DON’T HAVE TO FIGURE IT ALL OUT ALONE" title="A little help. A clearer way forward.">Explore assistance for preparing documents and understanding your next steps.</PageHeading><div className="agents-toolbar"><Badge>Illustrative demo profiles</Badge><Select label="Choose a city" value={city} onChange={e=>setCity(e.target.value)}><option>All cities</option>{[...new Set(agents.map(a=>a.city))].map(c=><option key={c}>{c}</option>)}</Select></div><div className="grid-3">{agents.filter(a=>city==='All cities'||a.city===city).map((agent,i)=><article className="card agent-card" key={agent._id}><Avatar name={agent.name} index={i}/><Badge>Demo profile</Badge><h2>{agent.name}</h2><p className="icon-text"><MapPin size={16}/>{agent.city}</p><p className="icon-text"><Languages size={16}/>{agent.languages.join(', ')}</p><div className="agent-specialties">{agent.specialties.map(s=><span key={s}>{s}</span>)}</div><Button to={`/agents/${agent._id}`} variant="secondary" className="full-width" arrow>View Profile</Button></article>)}</div><p className="sandbox-note">Fictional profiles with illustrated avatars. No real agents are verified or contacted in this demo.</p></div>;}
export function AgentDetail(){const {id}=useParams();const {user}=useApp();const resource=useResource(`agent-${id}`,()=>api.agent(id));const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);if(resource.loading)return <Loading label="Opening this assistance profile…"/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;const agent=resource.data.data;async function submit(e){e.preventDefault();setBusy(true);setError('');try{const agreement=(await api.consent({purpose:'AGENT_ASSISTANCE',documentIds:[],sharedWith:id,version:'1.0'})).consent;await api.requestAgent(id,agreement._id);setSuccess(true);}catch(e){setError(e.message);}finally{setBusy(false);}}return <div className="container narrow page"><PageHeading eyebrow="EXPERT ASSISTANCE · DEMO PROFILE" title={agent.name} back="/agents">A little guidance for a more confident application.</PageHeading><section className="card agent-detail"><Avatar name={agent.name}/><Badge>Demo profile</Badge><p>{agent.description}</p><DetailRow label="City">{agent.city}</DetailRow><DetailRow label="Languages">{agent.languages.join(', ')}</DetailRow><DetailRow label="Experience">Not provided in this demo</DetailRow><DetailRow label="Rating">No reviews available</DetailRow><h3>How this profile can help</h3><CheckList items={agent.specialties}/>{user?<form onSubmit={submit}><label className="consent-check"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I consent to requesting assistance from this selected demo partner. No real person will be contacted.</span></label>{error&&<Notice tone="error">{error}</Notice>}<Button type="submit" disabled={!consent} busy={busy} className="full-width" arrow>{busy?'Preparing your request…':'Request assistance'}</Button></form>:<Button to={`/login?next=${encodeURIComponent(`/agents/${id}`)}`} className="full-width" arrow>Sign in to request assistance</Button>}<p className="sandbox-note"><ShieldCheck size={16}/> Your consent is yours to manage in Settings.</p></section><Modal open={success} title="Your assistance request is saved." onClose={()=>setSuccess(false)}><div className="success-symbol"><Check size={38}/></div><p>This is a sandbox request. No real agent has been contacted.</p><Button to="/dashboard" onClick={()=>setSuccess(false)} className="full-width" arrow>Go to my dashboard</Button></Modal></div>;}
