import { useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { FileCheck2, UploadCloud, ArrowRight, Check, AlertCircle, FileText, ShieldCheck, LoaderCircle, X, CircleHelp } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { api } from '../services/api';
import { useResource } from '../hooks/useResource';
import { Button, PageHeading, Loading, Problem, Empty, Ring, Badge, Notice, DetailRow, SafeNote, Select, docNames, date } from '../components/UI';
const docTypes = Object.keys(docNames);
const descriptions = { AADHAAR: 'A clear identity document with your name and date of birth.', PAN: 'Make sure your name and PAN details are readable.', SALARY_SLIP: 'Include the employer, salary month, gross pay, and net pay.', BANK_STATEMENT: 'A readable statement covering at least 3 months.' };
const tidy = value => value.replaceAll('AADHAAR','Aadhaar').replaceAll('PAN','PAN card').replaceAll('SALARY_SLIP','salary slip').replaceAll('BANK_STATEMENT','bank statement');
const masked = value => /^XXXX XXXX \d{4}$|^[A-Z]{5}\*{4}[A-Z]$/.test(value || '') ? value : 'Hidden for privacy';
const safeName = value => value.replace(/\b\d{4}[ -]?\d{4}[ -]?(\d{4})\b/g,'XXXX XXXX $1').replace(/\b([A-Z]{5})\d{4}([A-Z])\b/gi,'$1****$2');
export function useDocuments() { const {user}=useApp();return useResource(`documents-${user._id}`,async()=>{const [docs,readiness]=await Promise.all([api.documents(),api.readiness()]);return{docs:docs.data,readiness};}); }
export function Documents() {
  const resource=useDocuments();const {selectedLoan}=useApp();
  if(resource.loading)return <Loading label="Checking your application readiness…"/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;
  const {docs,readiness}=resource.data;const nextType=docTypes.find(type=>!readiness.documents.some(d=>d.documentType===type&&d.analysis.status==='passed'))||'AADHAAR';
  return <div className="container page"><PageHeading eyebrow="A LITTLE PREPARATION GOES A LONG WAY" title="Your application, getting ready.">One clear checklist. One document at a time.</PageHeading><div className="readiness-layout"><section className="readiness-overview"><div className="eyebrow">APPLICATION READINESS</div><Ring value={readiness.overallScore} size={176}/><h2>{readiness.status==='Ready'?'You’re ready for your next step.':readiness.status==='Almost Ready'?'You’re getting close.':'Let’s get your documents ready.'}</h2><p>{readiness.status==='Ready'?'Your demo document checks are complete. Review your application whenever you’re ready.':'We’ll help you spot what’s missing and what needs a second look.'}</p><Button to={readiness.status==='Ready'&&selectedLoan?`/loans/${selectedLoan}/prepare`:`/documents/upload?type=${nextType}`} arrow>{readiness.status==='Ready'?'Continue Preparing':'Continue Preparing'}</Button><SafeNote>Checked only with your consent.</SafeNote></section><section className="document-checklist card"><div className="section-heading"><h2>Your document checklist</h2><Badge>{readiness.documents.filter(d=>d.analysis.status==='passed').length} of {docTypes.length} ready</Badge></div>{docTypes.map(type=>{const best=readiness.documents.find(d=>d.documentType===type);const uploaded=docs.filter(d=>d.documentType===type);const document=uploaded.find(d=>d._id===best?.analysis.documentId)||uploaded.at(-1);const passed=best?.analysis.status==='passed';return <Link key={type} to={document?`/documents/${document._id}`:`/documents/upload?type=${type}`} className="document-row"><div className={`document-status-icon ${passed?'ready':''}`}>{passed?<Check size={22}/>:<FileText size={22}/>}</div><div><strong>{docNames[type]}</strong><small>{passed?'Your document checks look good.':document?'Let’s take a closer look.':descriptions[type]}</small></div><Badge tone={passed?'green':document?'amber':'neutral'}>{passed?'Ready':document?'Needs Attention':'Missing'}</Badge><ArrowRight size={17}/></Link>;})}<div className="checklist-note"><CircleHelp size={17}/><p>This demo checks four document types. A real lender may request extra salary slips or employment proof.</p></div></section></div>{readiness.recommendations.length>0&&<details className="accordion"><summary>A little guidance for your next upload</summary><ul>{readiness.recommendations.map(r=><li key={r}>{tidy(r)}</li>)}</ul></details>}<p className="sandbox-note"><ShieldCheck size={16}/> Sandbox analysis — not UIDAI authentication.</p></div>;
}
export function DocumentUpload() {
  const [params]=useSearchParams();const navigate=useNavigate();const {setAnalyses}=useApp();
  const [type,setType]=useState(docTypes.includes(params.get('type'))?params.get('type'):'AADHAAR');const [file,setFile]=useState(null);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [uploaded,setUploaded]=useState(null);const [drag,setDrag]=useState(false);
  function choose(file) {setError('');setUploaded(null);if(!file)return;const valid=['application/pdf','image/png','image/jpeg'].includes(file.type);if(!valid){setError('Please choose a PDF, PNG, or JPG file.');setFile(null);return;}if(file.size>10*1024*1024){setError('This file is a little too large. Choose one under 10 MB.');setFile(null);return;}setFile(file);}
  async function submit(e) {e.preventDefault();if(!file||!consent)return;setError('');try{let doc=uploaded;if(!doc){setBusy('Uploading your document…');doc=(await api.upload(file,type)).document;setUploaded(doc);}setBusy('Checking your document…');const agreement=(await api.consent({purpose:'DOCUMENT_ANALYSIS',documentIds:[doc._id],sharedWith:'SubmitSafe',version:'1.0'})).consent;const result=await api.analyze(doc._id,agreement._id);setAnalyses(previous=>({...previous,[doc._id]:result.analysis}));navigate(`/documents/${doc._id}`);}catch(e){setError(e.message);}finally{setBusy('');}}
  return <div className="container narrow page"><PageHeading eyebrow="ONE DOCUMENT. ONE CLEAR NEXT STEP." title={`Let’s check your ${docNames[type].toLowerCase()}.`} back="/documents">Upload a clear photo or PDF. We’ll help you check the details.</PageHeading><form onSubmit={submit} className="card upload-card"><Select label="Document to check" value={type} disabled={!!busy} onChange={e=>{setType(e.target.value);setUploaded(null);setFile(null);}}>{docTypes.map(type=><option value={type} key={type}>{docNames[type]}</option>)}</Select><p className="muted">{descriptions[type]}</p><div className={`drop-zone ${drag?'dragging':''} ${file?'has-file':''}`} onDragOver={e=>{e.preventDefault();if(!busy)setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)choose(e.dataTransfer.files[0]);}}><input type="file" aria-label="Choose document" accept=".pdf,.png,.jpg,.jpeg" disabled={!!busy} onChange={e=>choose(e.target.files[0])}/><div className="upload-icon">{file?<FileCheck2 size={30}/>:<UploadCloud size={30}/>}</div><strong>{file?safeName(file.name):'Drop your file here, or browse'}</strong><span>{file?`${(file.size/1024).toFixed(0)} KB · Click to choose a different file`:'PDF, PNG or JPG · Up to 10 MB'}</span></div><label className="consent-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={!!busy} required/><span>I consent to SubmitSafe analyzing this document for readiness. I understand this is a sandbox check and can revoke consent in Settings.</span></label>{busy&&<div className="checking-panel" role="status"><LoaderCircle className="spin" size={22}/><div><strong>{busy}</strong><small>A careful look at readability and matching details.</small></div></div>}{error&&<Notice tone="error">{error}{uploaded&&<p>Your upload is saved. Retrying will check the same document.</p>}</Notice>}<Button type="submit" busy={!!busy} disabled={!file||!consent} className="full-width" arrow>{busy?'Checking…':uploaded?'Try document check again':'Upload & check document'}</Button><p className="sandbox-note"><ShieldCheck size={16}/> Sandbox analysis — not UIDAI authentication.</p><details className="plain-details"><summary>Tips for a clear check</summary><p>Use a synthetic demo document with the same name and date of birth as your profile. Keep all corners visible. Scanned PDFs may need a manual review; a clear PNG or JPG works better for those.</p><p>Original files are retained privately by the demo backend. They are not publicly accessible.</p></details></form></div>;
}
export function DocumentDetail() {
  const {id}=useParams();const resource=useDocuments();const {analyses,setAnalyses}=useApp();const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  if(resource.loading)return <Loading label="Opening your document check…"/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;
  const document=resource.data.docs.find(d=>d._id===id);if(!document)return <Empty title="We couldn’t find that document." to="/documents" action="Back to documents">Check your document list to continue.</Empty>;
  const analysis=analyses[id]||resource.data.readiness.documents.find(d=>d.analysis.documentId===id)?.analysis;const identity=['AADHAAR','PAN'].includes(document.documentType);
  async function recheck(){setBusy(true);setError('');try{const agreement=(await api.consent({purpose:'DOCUMENT_ANALYSIS',documentIds:[id],sharedWith:'SubmitSafe',version:'1.0'})).consent;const result=await api.analyze(id,agreement._id);setAnalyses(previous=>({...previous,[id]:result.analysis}));}catch(e){setError(e.message);}finally{setBusy(false);}}
  const checks=analysis?[['Readable',analysis.readability==='good'],['Name match',analysis.nameMatch],...(identity?[['Date of birth match',analysis.dobMatch],['Identity number detected',analysis.identifierDetected]]:[['Document type detected',analysis.documentDetected],...(document.documentType==='BANK_STATEMENT'?[['At least 3 months covered',(analysis.extractedFields?.monthsCovered||0)>=3]]:[['Salary month detected',analysis.extractedFields?.monthDetected]])])]:[];
  return <div className="container narrow page"><PageHeading eyebrow={docNames[document.documentType].toUpperCase()} title={analysis?'Document Check Complete':'Your document is uploaded.'} back="/documents">{analysis?.status==='passed'?'One more thing you can feel clearer about.':'Let’s make sure everything is easy to read and ready to go.'}</PageHeading><section className="card analysis-card">{analysis?<><div className="analysis-header"><div><Badge tone={analysis.status==='passed'?'green':'amber'}>{analysis.status==='passed'?'Ready':'Needs Attention'}</Badge><h2>{analysis.status==='passed'?'Looking good.':analysis.status==='manual_review'?'This needs a closer look.':'A few things to check.'}</h2>{analysis.maskedIdentifier&&<p className="masked-identifier">{masked(analysis.maskedIdentifier)}</p>}</div><Ring value={analysis.readinessScore} size={120}/></div><div className="analysis-checks">{checks.map(([label,ok])=><div key={label}><span>{label}</span>{ok===true?<span className="check-ok"><Check size={18}/> Yes</span>:<span className="check-warning"><AlertCircle size={17}/>{ok===false?'Needs attention':'Not confirmed'}</span>}</div>)}</div>{analysis.recommendations?.length>0&&<div className="recommendations"><h3>Your next steps</h3><ul>{analysis.recommendations.map(r=><li key={r}>{tidy(r)}</li>)}</ul></div>}<details className="plain-details"><summary>View check details</summary><DetailRow label="OCR / extraction confidence">{analysis.confidence}%</DetailRow><DetailRow label="Uploaded">{date(document.createdAt)}</DetailRow><DetailRow label="Document type">{docNames[document.documentType]}</DetailRow><DetailRow label="Status">{analysis.status.replaceAll('_',' ')}</DetailRow>{analysis.extractedFields?.monthsCovered!=null&&<DetailRow label="Statement coverage">{analysis.extractedFields.monthsCovered} months</DetailRow>}<p className="small muted">Confidence describes text extraction, not the probability that an identity is authentic.</p>{analysis.warnings?.map(w=><p key={w} className="small">{w}</p>)}</details></>:<p>This upload has no available check result yet. Give consent below to check it now.</p>}<p className="sandbox-note"><ShieldCheck size={16}/> Sandbox analysis — not UIDAI authentication.</p><div className="actions"><Button to="/documents" arrow>Continue Preparing</Button><Button to={`/documents/upload?type=${document.documentType}`} variant="secondary">Upload another</Button></div><details className="plain-details" open={!analysis}><summary>Check this document again</summary><label className="consent-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I consent to a new readiness check of this document.</span></label>{error&&<Notice tone="error">{error}</Notice>}<Button variant="secondary" onClick={recheck} disabled={!consent} busy={busy}>{busy?'Checking your document…':'Check document'}</Button></details></section></div>;
}
