import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, House, FileCheck2, ShieldCheck, ScanLine, SlidersHorizontal, Sprout, Sparkles, MousePointer2, CircleCheck } from 'lucide-react';
import { Button, SafeNote } from '../components/UI';
import { useResource } from '../hooks/useResource';
import { api } from '../services/api';
function HomeIllustration() { return <div className="hero-visual" aria-label="Illustration of a home and a clear document checklist"><div className="visual-label"><span/> A clearer path to your next chapter</div><div className="illustration-orbit orbit-one"/><div className="illustration-orbit orbit-two"/><svg className="house-art" viewBox="0 0 560 440" fill="none" aria-hidden="true"><ellipse cx="301" cy="387" rx="207" ry="27" fill="#c4d4b4" opacity=".48"/><circle cx="428" cy="103" r="37" fill="#f7f8d5"/><path d="M146 207 277 89 422 186 286 308Z" fill="#285143"/><path d="m277 89 0 20-114 105-17-7Z" fill="#50715b"/><path d="m167 210 113-99 112 81v154l-112 55-113-66Z" fill="#f6f5df"/><path d="m280 111 112 81v154l-112 55Z" fill="#e3e7cc"/><path d="m280 111 146 85 18-20L281 71 135 198l16 19Z" fill="#355c49"/><path d="m281 71 0 18 145 107 18-20Z" fill="#183f35"/><path d="m181 225 62-31v61l-62 33Z" fill="#bad1bd"/><path d="m184 228 56-27v50l-56 30Z" stroke="#fffdf0" strokeWidth="7"/><path d="m213 213 0 54m-29-13 56-28" stroke="#fffdf0" strokeWidth="5"/><path d="m311 246 42 18v84l-42 21Z" fill="#55735e"/><path d="m359 219 21 12v46l-21-5Z" fill="#bdd0b6"/><path d="m364 226 12 8v34l-12-3Z" stroke="#f8f7e7" strokeWidth="4"/><circle cx="343" cy="307" r="3" fill="#d9edaa"/><path d="m312 369 46-24 31 16-49 27Z" fill="#adc3a7"/><path d="m339 388 50-27 27 15-50 28Z" fill="#becfaf"/><path d="M105 355v-88m0 48c-41 0-54-27-39-44 29-10 40 15 39 44Zm0-33c-14-29-2-63 21-59 26 15 7 49-21 59Zm0 57c33 0 47-30 28-44-22-5-30 16-28 44Z" stroke="#57734e" strokeWidth="5" fill="#9bb87f"/><path d="m88 350 35 0-7 30-20 0Z" fill="#e5d9b4"/><path d="M429 354v-65m0 38c31-1 48-28 33-44-28-2-36 23-33 44Zm0-20c-30-2-38-28-22-38 22-1 23 22 22 38Z" fill="#8aa776" stroke="#57734e" strokeWidth="5"/><path d="m414 350 32 0-6 26-19 0Z" fill="#e5d9b4"/><path d="m188 363 26 14m-5-7 63 35" stroke="#99b08b" strokeWidth="3" strokeLinecap="round"/></svg><div className="floating-check"><span className="icon-tile"><FileCheck2 size={23}/></span><div><strong>A little preparation.</strong><span>A lot more confidence.</span></div><CircleCheck size={19}/></div><div className="floating-pill"><ShieldCheck size={17}/> Your next step, made simpler.</div><span className="visual-footnote">Product illustration · not a verification result</span></div>; }
export default function Landing() {
  const { data } = useResource('landing-lenders', api.loans);
  const steps = [[SlidersHorizontal, 'Tell us what you need', 'A few simple questions. No paperwork yet.'], [Sparkles, 'See suitable options', 'Understand what may work for you, and why.'], [FileCheck2, 'Prepare your documents', 'Spot the small things before they become surprises.'], [ArrowUpRight, 'Apply confidently', 'Take your next step with a clearer picture.']];
  return <>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> LESS GUESSWORK. MORE CONFIDENCE.</div><h1 tabIndex={-1}>Know before<br/>you <span>submit.</span><svg viewBox="0 0 280 18" aria-hidden="true"><path d="M3 12Q130-4 277 9" stroke="currentColor" strokeWidth="6" strokeLinecap="round" fill="none"/></svg></h1><p>Find suitable loans and government schemes, prepare your documents, and avoid application surprises.</p><div className="hero-actions"><Button to="/loans" arrow>Find a Loan</Button><Button to="/schemes" variant="secondary">Explore Schemes <ArrowUpRight size={17}/></Button></div><SafeNote>No pressure. Just a more informed next step.</SafeNote></div><HomeIllustration/></section>
    <div className="trust-strip container">{[[SlidersHorizontal,'Compare lenders'],[ScanLine,'Check documents'],[ShieldCheck,'Understand eligibility'],[ArrowUpRight,'Apply confidently']].map(([Icon,label])=><div key={label}><Icon size={19}/><span>{label}</span></div>)}</div>
    {data?.data?.length > 0 && <section className="lender-strip container"><p>ONE PLACE TO EXPLORE YOUR OPTIONS</p><div>{data.data.map(loan=><span key={loan._id}>{loan.name.replace(' Demo Home Loan','')}</span>)}</div><small>Illustrative lender products in our demo. No lender partnership is implied.</small></section>}
    <section className="how-section container"><div className="section-heading"><div><div className="eyebrow">A SIMPLE WAY FORWARD</div><h2>Big plans. Small, clear steps.</h2></div><p>From “where do I start?”<br/>to knowing what comes next.</p></div><div className="how-grid">{steps.map(([Icon,title,text],i)=><article key={title}><div className="step-icon"><Icon size={24}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="document-feature container"><div className="document-preview"><div className="preview-title"><div className="icon-tile"><FileCheck2 size={23}/></div><div><strong>A clearer application starts here.</strong><p>Your documents, one simple checklist.</p></div></div>{[['Identity documents','Make the details match'],['Income documents','Make the numbers readable'],['Bank statement','Check your statement coverage']].map(([a,b],i)=><div className="preview-row" key={a}><span className="preview-number">0{i+1}</span><div><strong>{a}</strong><small>{b}</small></div><ArrowRight size={17}/></div>)}<div className="preview-note"><ShieldCheck size={16}/> Readiness checks. Always with your consent.</div></div><div className="feature-copy"><div className="eyebrow">MEET YOUR APPLICATION’S HEAD START</div><h2>Small document checks.<br/>Fewer big surprises.</h2><p>A blurry photo. A name that doesn’t match. A missing statement. We help you spot what needs attention, before you submit.</p><Button to="/documents" variant="primary" arrow>Check my documents</Button><small>Sandbox readiness checks are not identity authentication.</small></div></section>
    <section className="scheme-teaser container"><div className="icon-tile"><Sprout size={28}/></div><div><div className="eyebrow">MORE POSSIBILITIES</div><h2>There may be more support<br/>than you think.</h2><p>Explore schemes for education, housing, business, and your next big idea.</p></div><Button to="/schemes" variant="secondary" arrow>Explore Schemes</Button></section>
    <section className="closing-cta container"><div><h2>Your next chapter deserves clarity.</h2><p>Let’s take the first step together.</p></div><Button to="/loans" variant="lime" arrow>Find my options</Button></section>
  </>;
}
