import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Check, Plus, X, SlidersHorizontal, Landmark, FileCheck2 } from 'lucide-react';
import { api } from '../services/api';
import { useResource } from '../hooks/useResource';
import { useApp } from '../context/AppContext';
import { Button, PageHeading, Loading, Problem, Empty, Ring, Badge, CheckList, DetailRow, Notice, money, docNames } from '../components/UI';
export function LenderMark({ name }) { return <span className="lender-mark" aria-hidden="true">{name.startsWith('Bank of') ? 'BOB' : name.split(' ')[0].slice(0,5)}</span>; }
const plainReason = reason => ({ 'Income meets the demo minimum': 'Income fits the demo range', 'Age and age at maturity fit the demo range': 'Age and tenure fit the guidelines', 'Amount and tenure fit the demo limits': 'Your amount and tenure are supported', 'Self-reported credit score meets the demo guideline': 'Credit profile looks suitable', 'Employment type fits the demo product': 'Employment type is supported', 'Estimated total EMI is within 50% of income': 'Estimated EMI fits your income' }[reason] || reason);
export function useLoan(id) {
  const { loanProfile } = useApp();
  return useResource(`loan-${id}-${JSON.stringify(loanProfile)}`, async () => {
    if (loanProfile) { const results = await api.matchLoans(loanProfile); const loan = results.data.find(item=>item._id===id); if (loan) return loan; }
    return (await api.loan(id)).data;
  });
}
function LoanCard({ loan, selected, toggle, tenure, choose }) { return <article className="loan-card"><div className="loan-card-top"><div className="lender-title"><LenderMark name={loan.name}/><div><span className="eyebrow">{loan.loanType} LOAN · DEMO</span><h2>{loan.name.replace(' Demo Home Loan','')}</h2></div></div><div className="match-mini"><Ring value={loan.matchScore} size={62} label={`${loan.name} match score`}/><span>{loan.matchScore>=80?'Strong match':loan.potentialMatch?'Potential match':'Worth reviewing'}</span></div></div><div className="loan-metrics"><div><span>Indicative interest</span><strong>{loan.interestRateMin.toFixed(2)}<small>% p.a.</small></strong></div><div><span>Approx. monthly EMI</span><strong>{money(loan.approxMonthlyEmi)}</strong></div><div><span>Your tenure</span><strong>{tenure}<small> years</small></strong></div><div><span>Processing fee</span><strong>{loan.processingFee}<small>%</small></strong></div></div><CheckList items={loan.reasons.slice(0,3).map(plainReason)}/><div className="loan-card-actions"><Button to={`/loans/${loan._id}`} variant="text">View Details <ArrowRight size={15}/></Button><label className={`compare-checkbox ${selected?'selected':''}`}><input type="checkbox" checked={selected} onChange={toggle}/>{selected?<Check size={15}/>:<Plus size={15}/>}Compare</label><Button to={`/loans/${loan._id}/prepare`} onClick={choose} arrow>Prepare Application</Button></div></article>; }
export function LoanResults() {
  const { loanProfile, compareIds, setCompareIds, setNotice, setSelectedLoan } = useApp(); const [sort,setSort] = useState('match');
  const resource = useResource(`matches-${JSON.stringify(loanProfile)}`, ()=>loanProfile?api.matchLoans(loanProfile):Promise.resolve(null));
  if (!loanProfile) return <div className="container"><Empty title="Let’s find your fit first." to="/loans" action="Find a Loan">A few simple answers help us show useful matches.</Empty></div>;
  if (resource.loading) return <Loading label="Finding suitable lenders…"/>; if(resource.error) return <Problem error={resource.error} retry={resource.reload}/>;
  const loans = [...resource.data.data].sort((a,b)=>sort==='emi'?a.approxMonthlyEmi-b.approxMonthlyEmi:b.matchScore-a.matchScore);
  const count = loans.filter(l=>l.potentialMatch).length;
  const toggle = id => { if(compareIds.includes(id))setCompareIds(compareIds.filter(value=>value!==id));else if(compareIds.length<3)setCompareIds([...compareIds,id]);else setNotice('Choose up to 3 lenders to keep your comparison simple.'); };
  return <div className="container page results-page"><PageHeading eyebrow="YOUR OPTIONS, A LITTLE CLEARER" title={count?`We found ${count} potential matches for you.`:'A few options to look at more closely.'} action={<Button to={loanProfile.loanType==='EDUCATION'?'/loans/education':'/loans/home'} variant="secondary"><SlidersHorizontal size={16}/> Edit answers</Button>}>Results are indicative. Final eligibility depends on the lender.</PageHeading><div className="results-toolbar"><div className="summary-chips"><span>{loanProfile.loanType === 'EDUCATION' ? 'Education loan' : 'Home loan'}</span><span>{money(loanProfile.loanAmount)}</span><span>{loanProfile.tenureYears} years</span></div><label className="sort-control">Sort by <select aria-label="Sort loan results" value={sort} onChange={e=>setSort(e.target.value)}><option value="match">Best match based on configured preferences</option><option value="emi">Lowest EMI</option></select></label></div><div className="loan-results-layout"><div className="loan-list">{loans.map(loan=><LoanCard key={loan._id} loan={loan} tenure={loanProfile.tenureYears} selected={compareIds.includes(loan._id)} toggle={()=>toggle(loan._id)} choose={()=>setSelectedLoan(loan._id)}/>)}</div><aside className="results-aside"><div className="icon-tile"><FileCheck2 size={24}/></div><h3>A match is just<br/>the beginning.</h3><p>A clear, complete set of documents helps you take the next step with confidence.</p><Link to="/documents">Check your readiness <ArrowRight size={16}/></Link><hr/><small>These are illustrative demo products. Rates are not current lender quotations.</small></aside></div>{compareIds.length>0&&<div className="compare-dock"><div><strong>{compareIds.length} of 3 lenders selected</strong><span>See your options side by side.</span></div><Button to={compareIds.length>=2?'/loans/compare':undefined} disabled={compareIds.length<2}>Compare lenders <ArrowRight size={16}/></Button><button className="icon-button" aria-label="Clear comparison" onClick={()=>setCompareIds([])}><X size={19}/></button></div>}</div>;
}
export function LoanCompare() {
  const { compareIds, loanProfile, setSelectedLoan } = useApp();
  const resource = useResource(`compare-${compareIds.join(',')}-${JSON.stringify(loanProfile)}`,()=>loanProfile&&compareIds.length>=2?api.compareLoans(compareIds.slice(0,3),loanProfile):Promise.resolve(null));
  if(!loanProfile||compareIds.length<2)return <Empty title="Pick two or three lenders." to="/loans/results" action="Choose lenders">Select Compare on the options you’d like to look at together.</Empty>;
  if(resource.loading)return <Loading label="Bringing your options together…"/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;
  const loans=resource.data.data;
  const rows=[['Indicative interest',l=>`${l.interestRateMin.toFixed(2)}–${l.interestRateMax.toFixed(2)}% p.a.`],['Approx. monthly EMI',l=>money(l.approxMonthlyEmi)],['Processing fee',l=>`${l.processingFee}%`],['Your tenure',()=>`${loanProfile.tenureYears} years`],['Required documents',l=>l.documentsRequired.map(d=>docNames[d]||d).join(', ')],['Prepayment',l=>l.prepaymentCharges],['Match score',l=>`${l.matchScore}%`]];
  return <div className="container page"><PageHeading eyebrow="SIDE BY SIDE" title="A little comparison. A clearer choice." back="/loans/results">Just the details that matter. All figures are indicative demo values.</PageHeading><div className="comparison-table card"><table><thead><tr><th>What matters</th>{loans.map(l=><th key={l._id}><LenderMark name={l.name}/><h2>{l.name.replace(' Demo Home Loan','')}</h2><Badge tone="green">{l.matchScore}% match</Badge></th>)}</tr></thead><tbody>{rows.map(([label,fn])=><tr key={label}><th scope="row">{label}</th>{loans.map(l=><td key={l._id}>{fn(l)}</td>)}</tr>)}<tr><th/><>{loans.map(l=><td key={l._id}><Button to={`/loans/${l._id}/prepare`} onClick={()=>setSelectedLoan(l._id)} arrow>Prepare Application</Button></td>)}</></tr></tbody></table></div><div className="comparison-mobile">{loans.map(l=><article className="card" key={l._id}><div className="lender-title"><LenderMark name={l.name}/><h2>{l.name.replace(' Demo Home Loan','')}</h2></div>{rows.map(([label,fn])=><DetailRow key={label} label={label}>{fn(l)}</DetailRow>)}<Button to={`/loans/${l._id}/prepare`} className="full-width" onClick={()=>setSelectedLoan(l._id)}>Prepare Application</Button></article>)}</div><details className="accordion"><summary>More Details</summary><div className="grid-3">{loans.map(l=><div key={l._id}><h3>{l.name}</h3><DetailRow label="Illustrative APR">{l.apr.toFixed(2)}%</DetailRow><DetailRow label="Minimum monthly income">{money(l.minIncome)}</DetailRow><DetailRow label="Maximum loan">{money(l.maxLoan)}</DetailRow><DetailRow label="Age range">{l.minAge}–{l.maxAge}</DetailRow></div>)}</div></details></div>;
}
export function LoanDetail() {
  const { id }=useParams();const {loanProfile,setSelectedLoan}=useApp();const resource=useLoan(id);
  if(resource.loading)return <Loading label="Getting the details…"/>;if(resource.error)return <Problem error={resource.error} retry={resource.reload}/>;const loan=resource.data;
  return <div className="container page"><PageHeading eyebrow={`${loan.loanType} LOAN · DEMO PRODUCT`} title={loan.name} back={loanProfile?'/loans/results':'/loans'}>A closer look, so you can decide what feels right.</PageHeading><div className="detail-layout"><div><section className="card"><h2>Overview</h2><div className="loan-metrics"><div><span>Indicative interest</span><strong>{loan.interestRateMin.toFixed(2)}<small>% p.a.</small></strong></div><div><span>Approx. monthly EMI</span><strong>{money(loan.approxMonthlyEmi)}</strong></div></div><CheckList items={loan.features}/></section><section className="card"><h2>Why it may suit you</h2>{loan.reasons?<CheckList items={loan.reasons.map(plainReason)}/>:<p>Answer a few questions to see how this loan fits your needs.</p>}</section><section className="card"><h2>Costs</h2><DetailRow label="Interest range">{loan.interestRateMin.toFixed(2)}–{loan.interestRateMax.toFixed(2)}% p.a.</DetailRow><DetailRow label="Processing fee">{loan.processingFee}% of loan amount</DetailRow><DetailRow label="Illustrative APR">{loan.apr.toFixed(2)}%</DetailRow><p className="muted small">Estimated EMI excludes fees. Confirm the final costs with the lender.</p></section><section className="card"><h2>Eligibility</h2><DetailRow label="Minimum monthly income">{money(loan.minIncome)}</DetailRow><DetailRow label="Age range (including maturity)">{loan.minAge}–{loan.maxAge} years</DetailRow><DetailRow label="Maximum tenure">{loan.maxTenureYears} years</DetailRow><DetailRow label="Recommended credit score">{loan.recommendedCreditScore}+</DetailRow></section><section className="card"><h2>Documents</h2><CheckList items={loan.documentsRequired.map(d=>docNames[d]||d)}/></section><details className="accordion" open><summary>Important Conditions</summary><p>{loan.prepaymentCharges}</p>{loan.warnings?.map(w=><p key={w}>{w}</p>)}<p>Demo data only. This is not an approval or a current lender quotation. No lender partnership is implied.</p></details></div><aside className="sticky-card card"><LenderMark name={loan.name}/><h2>Your next step,<br/>a little clearer.</h2>{loan.matchScore!=null&&<Ring value={loan.matchScore} label="Loan match score"/>}<p>Prepare your documents and review everything in one place.</p><Button to={loanProfile?`/loans/${id}/prepare`:`/loans/${loan.loanType.toLowerCase()}?product=${id}`} onClick={()=>setSelectedLoan(id)} className="full-width" arrow>{loanProfile?'Prepare Application':'Find my match'}</Button><small>Final eligibility depends on the lender.</small></aside></div></div>;
}
