import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { House, CarFront, GraduationCap, Wallet, ArrowLeft, Check, CircleHelp } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { Button, Field, Select, PageHeading, Steps, SafeNote, Notice, occupations } from '../components/UI';
export const loanTypes = [['home', 'Home Loan', 'A place to call your own.', House], ['personal', 'Personal Loan', 'For life’s other big plans.', Wallet], ['education', 'Education Loan', 'Invest in what’s ahead.', GraduationCap], ['car', 'Car Loan', 'Your next journey starts here.', CarFront]];
export default function LoanWizard({ type = null }) {
  const { user, loanProfile, setLoanProfile, setCompareIds } = useApp(); const navigate = useNavigate();
  const [step, setStep] = useState(type ? 1 : 0); const [chosen, setChosen] = useState(type || 'home');
  const [form, setForm] = useState({ name: user?.name || loanProfile?.name || '', age: loanProfile?.age || '', city: user?.profile?.city || loanProfile?.city || '', employmentType: loanProfile?.employmentType || 'salaried', monthlyIncome: loanProfile?.monthlyIncome || '', annualIncome: '', incomeMode: 'monthly', loanAmount: loanProfile?.loanAmount || '', tenureYears: loanProfile?.tenureYears || 20, existingEmi: loanProfile?.existingEmi ?? 0, creditScoreRange: loanProfile?.creditScoreRange || 'unknown' });
  const update = key => event => setForm({ ...form, [key]: event.target.value });
  const [error, setError] = useState('');
  function next(event) {
    event.preventDefault(); setError('');
    if (step === 0 && chosen !== 'home') { navigate(`/loans/${chosen}`); return; }
    if (step < 4) { setStep(step + 1); return; }
    const payload = { name: form.name.trim(), age: Number(form.age), city: form.city.trim(), employmentType: form.employmentType,
      ...(form.incomeMode === 'monthly' ? { monthlyIncome: Number(form.monthlyIncome) } : { annualIncome: Number(form.annualIncome) }), loanAmount: Number(form.loanAmount), tenureYears: Number(form.tenureYears), existingEmi: Number(form.existingEmi), creditScoreRange: form.creditScoreRange };
    setLoanProfile(payload); setCompareIds([]); navigate('/loans/results');
  }
  if (type && type !== 'home') { const info = loanTypes.find(t => t[0] === type); return <div className="container narrow"><PageHeading title={`${info?.[1] || 'Loan'} options are on the way.`} back="/loans">We’re starting with home loans. This loan type isn’t available in the current demo.</PageHeading><div className="card empty-state"><House size={42}/><Button to="/loans/home" arrow>Explore home loans</Button></div></div>; }
  const titles = ['What’s your next big step?', 'A little about you.', 'Let’s talk income.', 'What do you have in mind?', 'One last thing. Your credit score.'];
  const subtitles = ['Choose what you’re planning. We’ll help you find a way forward.', 'Just the basics, so your options feel a little more personal.', 'This helps us find options that fit your everyday life.', 'A few numbers to make your options more useful.', 'An estimate is fine. You can also choose “I’m not sure”.'];
  return <div className="wizard-shell container"><div className="wizard-topline"><span className="eyebrow">FIND YOUR FIT</span><span>About 2 minutes <span className="small-dot"/></span></div><Steps current={step} labels={['Your goal', 'About you', 'Income', 'Your loan', 'Credit score']}/><form onSubmit={next} className="wizard-card" key={step}><div className="step-caption">STEP {step + 1} OF 5</div><h1 tabIndex={-1}>{titles[step]}</h1><p className="wizard-subtitle">{subtitles[step]}</p>
    {step === 0 && <div className="loan-types">{loanTypes.map(([key, title, subtitle, Icon]) => <label key={key} className={`choice-card ${chosen === key ? 'selected' : ''}`}><input type="radio" name="loanType" value={key} checked={chosen === key} onChange={() => setChosen(key)}/><Icon size={27}/><strong>{title}</strong><small>{subtitle}</small>{key !== 'home' && <span className="coming-label">Coming soon</span>}<span className="choice-dot">{chosen === key && <Check size={12}/>}</span></label>)}</div>}
    {step === 1 && <div className="form-stack"><Field label="Full name" autoComplete="name" required maxLength={120} value={form.name} onChange={update('name')}/><div className="form-grid"><Field label="Age" type="number" min="18" max="100" required value={form.age} onChange={update('age')}/><Field label="City" autoComplete="address-level2" required maxLength={120} value={form.city} onChange={update('city')}/></div></div>}
    {step === 2 && <div className="form-stack"><Select label="Employment" value={form.employmentType} onChange={update('employmentType')}>{occupations.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select><fieldset className="segmented"><legend>How would you like to enter your income?</legend>{['monthly','annual'].map(value=><label className={form.incomeMode===value?'selected':''} key={value}><input type="radio" name="incomeMode" checked={form.incomeMode===value} onChange={()=>setForm({...form,incomeMode:value})}/>{value==='monthly'?'Monthly income':'Annual income'}</label>)}</fieldset><Field label={form.incomeMode === 'monthly' ? 'Monthly income' : 'Annual income'} type="number" prefix="₹" min="0" max="10000000000" required value={form.incomeMode === 'monthly' ? form.monthlyIncome : form.annualIncome} onChange={update(form.incomeMode === 'monthly' ? 'monthlyIncome' : 'annualIncome')} hint="Enter your income before deductions."/></div>}
    {step === 3 && <div className="form-stack"><Field label="Loan amount" type="number" prefix="₹" min="1000" max="10000000000" required value={form.loanAmount} onChange={update('loanAmount')} placeholder="e.g. 30,00,000"/><div className="form-grid"><Field label="Tenure (years)" type="number" min="1" max="40" required value={form.tenureYears} onChange={update('tenureYears')}/><Field label="Existing monthly EMI" type="number" prefix="₹" min="0" max="10000000000" required value={form.existingEmi} onChange={update('existingEmi')} hint="Enter 0 if you don’t have any."/></div></div>}
    {step === 4 && <div className="credit-choices">{[['unknown', 'I’m not sure', 'You can still explore your options.'], ['550-649','Below 650','Building your credit profile'], ['650-699','650–699','A little room to grow'], ['700-749','700–749','A good starting point'], ['750-799','750+','A strong starting point']].map(([value,label,hint])=><label className={`credit-choice ${form.creditScoreRange===value?'selected':''}`} key={value}><input type="radio" name="credit" value={value} checked={form.creditScoreRange===value} onChange={update('creditScoreRange')}/><span><strong>{label}</strong><small>{hint}</small></span>{form.creditScoreRange===value&&<Check size={18}/>}</label>)}<SafeNote>This step won’t check or affect your credit score.</SafeNote></div>}
    {error && <Notice tone="error">{error}</Notice>}<div className="wizard-actions">{step>0?<Button variant="text" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Back</Button>:<span/>}<Button type="submit" arrow>{step===4?'Find Matches':'Continue'}</Button></div></form><p className="wizard-footnote"><CircleHelp size={15}/> Indicative matches, never a promise of approval.</p></div>;
}
