import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import request from 'supertest';
import { getConfig } from '../config/index.js';
import { Store } from '../services/store.js';
import { createApp } from '../app.js';
import { seed } from '../seed/data.js';
import { pdf, documentLines, sampleProfile } from './helpers.js';

test('complete backend workflow and access controls', async t => {
  const uploadDir = await fs.mkdtemp(path.join(os.tmpdir(), 'submitsafe-test-'));
  const config = { ...getConfig({}), uploadDir, maxUploadBytes: 1024 * 1024 };
  const store = new Store(config); await store.connect(); await seed(store); await seed(store);
  t.after(async () => { await store.close(); await fs.rm(uploadDir, { recursive: true, force: true }); });
  const app = createApp({ config, store });
  const api = request(app);
  const health = await api.get('/api/health').expect(200); assert.equal(health.body.databaseStatus, 'mock-memory');
  assert.ok(health.headers['content-security-policy']);
  await api.get('/api/loans').set('Origin', 'https://untrusted.example').expect(403);
  await api.get('/api/user/me').expect(401);
  await api.get('/api/user/me').set('Authorization', 'Bearer invalid').expect(401);
  await api.post('/api/auth/register').send({ name: 'Test', email: 'invalid', password: '123' }).expect(400);
  await api.post('/api/auth/register').send({ name: 'Test', email: 'admin@example.test', password: 'Password1!', role: 'admin' }).expect(400);
  const registration = await api.post('/api/auth/register').send({ name: 'Test Person', email: 'TEST@example.test', password: 'Password1!', profile: { dob: '1995-01-01' } }).expect(201);
  assert.equal(registration.body.user.role, 'user'); assert.equal(registration.body.user.passwordHash, undefined);
  const token = registration.body.token; const auth = { Authorization: `Bearer ${token}` };
  await api.post('/api/auth/register').send({ name: 'Test Person', email: 'test@example.test', password: 'Password1!' }).expect(409);
  await api.post('/api/auth/login').send({ email: 'test@example.test', password: 'wrong' }).expect(401);
  await api.post('/api/auth/login').send({ email: 'test@example.test', password: 'Password1!' }).expect(200);
  await api.post('/api/auth/login').send({ email: 'demo@submitsafe.in', password: 'Demo@123' }).expect(200);
  await api.get('/api/user/me').set(auth).expect(200);
  const otp = (await api.post('/api/auth/send-otp').send({ phone: '+919876543210' }).expect(200)).body;
  await api.post('/api/auth/send-otp').send({ phone: '+919876543210' }).expect(429);
  await api.post('/api/auth/verify-otp').send({ phone: '+919876543210', challengeId: otp.challengeId, otp: '000000' }).expect(400);
  await api.post('/api/auth/verify-otp').send({ phone: '+919876543210', challengeId: otp.challengeId, otp: '123456' }).expect(200);
  await api.post('/api/auth/verify-otp').send({ phone: '+919876543210', challengeId: otp.challengeId, otp: '123456' }).expect(400);
  const loans = (await api.get('/api/loans').expect(200)).body.data; assert.equal(loans.length, 6);
  assert.ok(loans.every(l => l.dataMode === 'DEMO'));
  await api.get(`/api/loans/${loans[0]._id}`).expect(200); await api.get('/api/loans/bad-id').expect(400);
  const matched = (await api.post('/api/loans/match').send(sampleProfile).expect(200)).body.data;
  assert.equal(matched[0].matchScore, 100); assert.equal(matched[0].approved, undefined);
  await api.post('/api/loans/match').send({ ...sampleProfile, annualIncome: 1 }).expect(400);
  const compared = await api.post('/api/loans/compare').send({ loanProductIds: loans.slice(0, 2).map(l => l._id), profile: sampleProfile }).expect(200);
  assert.equal(compared.body.data.length, 2);
  await api.post('/api/loans/compare').send({ loanProductIds: [loans[0]._id, loans[0]._id], profile: sampleProfile }).expect(400);
  const schemes = (await api.get('/api/schemes').expect(200)).body.data; assert.ok(schemes.length >= 15);
  await api.get(`/api/schemes/${schemes[0]._id}`).expect(200);
  await api.post('/api/schemes/match').send({ age: 22, annualIncome: 200000, employmentType: 'student' }).expect(200);
  const agents = (await api.get('/api/agents').expect(200)).body.data; assert.equal(agents.length, 8);
  await api.get(`/api/agents/${agents[0]._id}`).expect(200);
  const initialReadiness = await api.get('/api/documents/readiness').set(auth).expect(200); assert.equal(initialReadiness.body.overallScore, 0);
  await api.post('/api/documents/upload').set(auth).field('documentType', 'AADHAAR').attach('file', Buffer.from('fake'), 'fake.exe').expect(415);
  await api.post('/api/documents/upload').set(auth).field('documentType', 'AADHAAR').attach('file', Buffer.from('not a pdf'), { filename: 'fake.pdf', contentType: 'application/pdf' }).expect(415);
  await api.post('/api/documents/upload').set(auth).field('documentType', 'AADHAAR').attach('file', Buffer.alloc(1024 * 1024 + 1), { filename: 'large.pdf', contentType: 'application/pdf' }).expect(413);
  const outsider = (await api.post('/api/auth/register').send({ name: 'Other User', email: 'other@example.test', password: 'Password1!' }).expect(201)).body;
  const otherAuth = { Authorization: `Bearer ${outsider.token}` };
  const documents = []; const consentIds = [];
  for (const [documentType, lines] of Object.entries(documentLines)) {
    const uploaded = await api.post('/api/documents/upload').set(auth).field('documentType', documentType).attach('file', pdf(lines), `${documentType}.pdf`).expect(201);
    const document = uploaded.body.document; documents.push(document);
    assert.equal(document.safeFileName, undefined); assert.ok(!JSON.stringify(uploaded.body).includes(uploadDir));
    await api.post(`/api/documents/${document._id}/analyze`).set(auth).send({}).expect(400);
    await api.post('/api/consents').set(otherAuth).send({ purpose: 'DOCUMENT_ANALYSIS', documentIds: [document._id] }).expect(404);
    const consent = (await api.post('/api/consents').set(auth).send({ purpose: 'DOCUMENT_ANALYSIS', documentIds: [document._id] }).expect(201)).body.consent;
    consentIds.push(consent._id);
    await api.post(`/api/documents/${document._id}/analyze`).set(otherAuth).send({ consentId: consent._id }).expect(404);
    const analyzed = await api.post(`/api/documents/${document._id}/analyze`).set(auth).send({ consentId: consent._id }).expect(200);
    assert.equal(analyzed.body.analysis.status, 'passed', JSON.stringify(analyzed.body));
    assert.ok(!JSON.stringify(analyzed.body).includes('1234 5678 9012')); assert.ok(!JSON.stringify(analyzed.body).includes('ABCDE1234F'));
  }
  const ready = await api.get('/api/documents/readiness').set(auth).expect(200); assert.equal(ready.body.status, 'Ready'); assert.equal(ready.body.overallScore, 100);
  assert.equal((await api.get('/api/documents').set(otherAuth).expect(200)).body.data.length, 0);
  await api.patch(`/api/consents/${consentIds[0]}/revoke`).set(auth).expect(200);
  await api.post(`/api/documents/${documents[0]._id}/analyze`).set(auth).send({ consentId: consentIds[0] }).expect(403);
  const share = (await api.post('/api/consents').set(auth).send({ purpose: 'LENDER_DATA_SHARE', documentIds: documents.map(d => d._id), sharedWith: loans[0]._id }).expect(201)).body.consent;
  const application = (await api.post('/api/applications').set(auth).send({ loanProductId: loans[0]._id, loanType: 'HOME', loanAmount: 3000000, tenure: 20, consentId: share._id }).expect(201)).body.application;
  assert.match(application.applicationCode, /^SS-HOME-\d{4}-\d{5}$/);
  await api.get('/api/applications').set(auth).expect(200);
  await api.get(`/api/applications/${application._id}`).set(auth).expect(200);
  await api.get(`/api/applications/${application._id}`).set(otherAuth).expect(404);
  await api.patch(`/api/applications/${application._id}/status`).set(auth).send({ status: 'Completed' }).expect(409);
  for (const status of ['Documents Pending', 'Ready', 'Submitted', 'Under Review', 'Completed']) {
    const response = await api.patch(`/api/applications/${application._id}/status`).set(auth).send({ status }).expect(200);
    assert.equal(response.body.application.status, status); assert.match(response.body.message, /No application has been sent/);
  }
  const agentConsent = (await api.post('/api/consents').set(auth).send({ purpose: 'AGENT_ASSISTANCE', sharedWith: agents[0]._id }).expect(201)).body.consent;
  await api.post(`/api/agents/${agents[1]._id}/request`).set(auth).send({ consentId: agentConsent._id }).expect(403);
  await api.post(`/api/agents/${agents[0]._id}/request`).set(auth).send({ consentId: agentConsent._id }).expect(201);
  await api.get('/api/consents').set(auth).expect(200);
  const audit = await store.find('AuditLog');
  for (const action of ['LOGIN', 'DOCUMENT_UPLOAD', 'DOCUMENT_ANALYSIS', 'CONSENT_GIVEN', 'APPLICATION_CREATED', 'APPLICATION_STATUS_CHANGED', 'AGENT_REQUESTED']) assert.ok(audit.some(a => a.action === action), action);
  assert.ok(!JSON.stringify(audit).includes('Password1!')); assert.ok(!JSON.stringify(audit).includes('1234 5678'));
  await api.get('/uploads/AADHAAR.pdf').expect(404);
});

test('LIVE API cannot silently use mock SMS or document results', async t => {
  const store = new Store(getConfig({})); await store.connect();
  t.after(() => store.close());
  const config = { ...getConfig({}), appMode: 'LIVE' };
  const api = request(createApp({ config, store }));
  const result = await api.post('/api/auth/send-otp').send({ phone: '+919876543210' }).expect(503);
  assert.equal(result.body.error.code, 'ProviderNotConfiguredError');
});
